### ISSUE TITLE
Write addToArray function

### ISSUE THREAD

**Issue by AlexOrga** [nss-evening-cohort-7/chatty-hylophobia#20]
# User Story
A user will see their new message displayed with previous message in the output

# Acceptance Criteria
**When** a user enters a new message
**Then** their new message displays below the previous ones

# Technical Data
- set a global variable named counter and set it to 6
- create function named addToArray with parameters username and inputValue
- set a variable named newObject
- write and object with keys "username", "message", and "timestamp"
- set username to username 
- set messages to inputValue
- set "timestamp" to ``` moment().format('MMMM Do YYYY, h:mm:ss'); ```
- set "id" to the counter 
- add 1 to the counter
- push this object to the messages array
- call buildDomString on the messages array

**Comment by Mehret17** [comment]
closes #42
