### ISSUE TITLE
Delete Button Event Listener

### ISSUE THREAD

**Issue by AlexOrga** [nss-evening-cohort-7/chatty-hylophobia#24]
# User Story
When a user clicks the delete button on an individual message the message should disappear

# Acceptance Criteria 
**When** An individual message's delete button is clicked
**Then** The message's object should be deleted from the messages array
**And** The updated array should be printed

# Technical Data
- Get the Id of the individual message you want to delete and set it to const 'id'
- Call removeFromArray(id) from data.js

**Comment by aprilrochelle** [comment]
👍
