### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by aprilrochelle** [nss-evening-cohort-7/chatty-hylophobia#51]
## The Story
As a developer, I need to update the README file so that a user understands the app

## Acceptace Criteria
**When** the group project is viewed on Github or opened in VS Code
**Then** there should be a ```README.md``` file with description
**And** screenshots
**And** instructions on how to run
**And** a list of contributors

## Technical Notes
- move current readme text to instructions.md
- update team readme.md

**Comment by Mehret17** [comment]
closes#51
